# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
